In [16]:
from twelvedata import TDClient

td = TDClient(apikey="f8ef5b79ba044ff5adfb4e44425caab5")

# request historical OHLCV
ts = td.time_series(
    symbol="XAU/USD",
    interval="1h",          # hourly candles
    outputsize=5000        # large enough to cover 2+ years (max 5000 per year per hour)
)

In [26]:

df = ts.as_pandas()

print(df.head())
print(df.tail())

                        open     high      low    close
datetime
2025-11-05 22:00:00  3957.58  3961.79  3952.72  3957.27
2025-11-05 21:00:00  3966.08  3966.08  3952.18  3957.36
2025-11-05 20:00:00  3971.86  3972.98  3958.12  3966.07
2025-11-05 19:00:00  3965.97  3977.86  3965.97  3971.87
2025-11-05 18:00:00  3961.02  3966.91  3957.19  3965.97
                           open        high         low       close
datetime
2025-02-11 19:00:00  2913.33008  2915.27002  2907.09009  2907.46997
2025-02-11 18:00:00  2918.05005  2918.39990  2907.45996  2913.54004
2025-02-11 17:00:00  2923.06006  2929.54004  2915.60010  2917.92993
2025-02-11 16:00:00  2916.23999  2923.81006  2915.46997  2923.04004
2025-02-11 15:00:00  2919.70996  2920.70996  2915.09009  2916.39990

In [27]:
df.head()

                        open     high      low    close
datetime
2025-11-05 22:00:00  3957.58  3961.79  3952.72  3957.27
2025-11-05 21:00:00  3966.08  3966.08  3952.18  3957.36
2025-11-05 20:00:00  3971.86  3972.98  3958.12  3966.07
2025-11-05 19:00:00  3965.97  3977.86  3965.97  3971.87
2025-11-05 18:00:00  3961.02  3966.91  3957.19  3965.97

In [28]:
df.tail()

                           open        high         low       close
datetime
2025-02-11 19:00:00  2913.33008  2915.27002  2907.09009  2907.46997
2025-02-11 18:00:00  2918.05005  2918.39990  2907.45996  2913.54004
2025-02-11 17:00:00  2923.06006  2929.54004  2915.60010  2917.92993
2025-02-11 16:00:00  2916.23999  2923.81006  2915.46997  2923.04004
2025-02-11 15:00:00  2919.70996  2920.70996  2915.09009  2916.39990

In [29]:
df.shape

(5000, 4)

In [30]:
df.reset_index(inplace=True)

In [31]:
df.head()

             datetime     open     high      low    close
0 2025-11-05 22:00:00  3957.58  3961.79  3952.72  3957.27
1 2025-11-05 21:00:00  3966.08  3966.08  3952.18  3957.36
2 2025-11-05 20:00:00  3971.86  3972.98  3958.12  3966.07
3 2025-11-05 19:00:00  3965.97  3977.86  3965.97  3971.87
4 2025-11-05 18:00:00  3961.02  3966.91  3957.19  3965.97

In [32]:
df.to_csv("/Users/mac/Desktop/Upwork/GoldSignalGenerator/Artifacts/twelve_data01.csv")